POST /api/users HTTP/1.1
Content-Type: application/json
Host: localhost:3333
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RpZ28iOiIzYjQ2MzRlZi1mNmUzLTRmNTMtOGRmYi1jNGU0NTgyZDdlY2EiLCJpYXQiOjE2MTg0MDk4MzEsImV4cCI6MTYxODQ5NjIzMX0.UzAH-hbsrNMWs6RTdZXWYxiGO0fDqsnzLfV6mrWbNy4
Content-Length: 534

{
	"employeeProfile": {
		"dataContrato": "2020-01-01",
		"salario": 1199.77,
		"senha": "senha123",
        "medicProfile": {
            "crm": "123665",
            "especialidade": "psiquiatra"
        }
	},
	"nome": "Joao",
	"email": "joao123@cefet.com",
	"telefone": "319999999",
	"endereco": {
		"cep": "31170543",
		"logradouro": "rua São João",
		"bairro": "cidade nova",
		"cidade": "Belo Horizonte",
		"estado": "MG"
	}
}
